version: '3.5'

services:
  fastapi:
    container_name: aipiping
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - OPENAI_API_KEY
    restart: unless-stopped
